"""Bus matrix exporter for conceptual models.

v1.0: Simplified without realized_by - shows relationships only.
"""

from typing import TextIO

from dbt_conceptual.exporter._templates import BUS_MATRIX_CSS, HTML_CLOSE, html_head
from dbt_conceptual.state import ProjectState


def export_bus_matrix(state: ProjectState, output: TextIO) -> None:
    """Export bus matrix as HTML table.

    Note: v1.0 removed realized_by from relationships. This export now
    shows a relationship summary instead of the traditional bus matrix.
    The full bus matrix will return in a future version.

    Args:
        state: Project state with concepts and relationships
        output: Text stream to write HTML to
    """
    # Sort relationships for consistent output
    relationships_list = sorted(
        state.relationships.items(), key=lambda x: (x[1].from_concept, x[1].name)
    )

    # Calculate statistics
    total_relationships = len(relationships_list)
    complete_relationships = sum(
        1
        for _rid, r in relationships_list
        if r.get_status(state.concepts) == "complete"
    )

    output.write(html_head("dbt-conceptual Relationships", BUS_MATRIX_CSS))
    output.write("""
    <div class="container">
        <h1>Relationships</h1>
        <p class="subtitle">Generated by dbt-conceptual</p>

        <div class="info">
            <h2>About Relationships</h2>
            <p>
                Relationships define how concepts connect to each other.
                A relationship is "complete" when both its endpoints are defined concepts.
            </p>
        </div>

        <div class="stats">
            <div class="stat">
                <div class="stat-label">Total Relationships</div>
                <div class="stat-value">""")
    output.write(str(total_relationships))
    output.write("""</div>
            </div>
            <div class="stat">
                <div class="stat-label">Complete</div>
                <div class="stat-value">""")
    output.write(str(complete_relationships))
    output.write("""</div>
            </div>
        </div>
""")

    if not relationships_list:
        output.write("""
        <div class="empty-state">
            <div class="empty-state-icon">🔗</div>
            <p>No relationships defined</p>
            <p style="font-size: 0.875rem; margin-top: 0.5rem; color: #999;">
                Add relationships to your conceptual.yml to see them here
            </p>
        </div>
""")
    else:
        output.write("""
        <div class="matrix-container">
            <table>
                <thead>
                    <tr>
                        <th>From</th>
                        <th>Verb</th>
                        <th>To</th>
                        <th>Cardinality</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
""")

        # Write relationship rows
        for _rel_id, rel in relationships_list:
            status = rel.get_status(state.concepts)
            status_class = "status-complete" if status == "complete" else "status-stub"
            status_icon = "✓" if status == "complete" else "○"

            output.write("                    <tr>\n")
            output.write(f"                        <td>{rel.from_concept}</td>\n")
            output.write(
                f"                        <td><strong>{rel.verb}</strong></td>\n"
            )
            output.write(f"                        <td>{rel.to_concept}</td>\n")
            output.write(f"                        <td>{rel.cardinality}</td>\n")
            output.write(
                f'                        <td class="{status_class}">{status_icon} {status}</td>\n'
            )
            output.write("                    </tr>\n")

        output.write("""                </tbody>
            </table>
        </div>
""")

    output.write(HTML_CLOSE)
