"""Coverage report exporter for conceptual models.

v1.0: Simplified model - single models[] array.
"""

from typing import TextIO

from dbt_conceptual.exporter._stats import calculate_coverage_stats
from dbt_conceptual.exporter._templates import COVERAGE_CSS, HTML_CLOSE, html_head
from dbt_conceptual.state import ConceptState, ProjectState


def export_coverage(state: ProjectState, output: TextIO) -> None:
    """Export coverage report as HTML dashboard.

    Args:
        state: Project state with concepts and relationships
        output: Text stream to write HTML to
    """
    # Calculate statistics via shared helper
    stats = calculate_coverage_stats(state)

    completion_pct = stats["concepts"]["completion_percent"]
    complete_concepts = stats["concepts"]["complete"]
    total_concepts = stats["concepts"]["total"]
    stub_concepts = stats["concepts"]["stub"]
    draft_concepts = stats["concepts"]["draft"]
    model_coverage_pct = stats["coverage"]["models"]["percent"]
    concepts_with_models = stats["coverage"]["models"]["count"]
    relationship_pct = stats["relationships"]["percent"]
    complete_relationships = stats["relationships"]["complete"]
    total_relationships = stats["relationships"]["total"]
    orphan_count = stats["orphans"]

    # Group concepts by domain
    domain_groups: dict[str, list[tuple[str, ConceptState]]] = {}
    for concept_id, concept in state.concepts.items():
        domain = concept.domain or "uncategorized"
        if domain not in domain_groups:
            domain_groups[domain] = []
        domain_groups[domain].append((concept_id, concept))

    # Find attention items
    incomplete_concepts = [
        (cid, c)
        for cid, c in state.concepts.items()
        if c.status != "complete" and (not c.domain or not c.owner or not c.definition)
    ]

    # Write HTML
    output.write(html_head("dbt-conceptual Coverage Report", COVERAGE_CSS))
    output.write("""
    <div class="container">
        <h1>Coverage Report</h1>
        <p class="subtitle">Generated by dbt-conceptual</p>

        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-label">Concept Completion</div>
                <div class="stat-value">""")
    output.write(f"{completion_pct}%")
    output.write("""</div>
                <div class="stat-secondary">""")
    output.write(f"{complete_concepts} of {total_concepts} concepts complete")
    output.write("""</div>
                <div class="progress-bar">
                    <div class="progress-fill" style="width: """)
    output.write(f"{completion_pct}%")
    output.write(""""></div>
                </div>
            </div>

            <div class="stat-card">
                <div class="stat-label">Model Coverage</div>
                <div class="stat-value">""")
    output.write(f"{model_coverage_pct}%")
    output.write("""</div>
                <div class="stat-secondary">""")
    output.write(f"{concepts_with_models} concepts have models")
    output.write("""</div>
                <div class="progress-bar">
                    <div class="progress-fill" style="width: """)
    output.write(f"{model_coverage_pct}%")
    output.write(""""></div>
                </div>
            </div>

            <div class="stat-card">
                <div class="stat-label">Relationships Complete</div>
                <div class="stat-value">""")
    output.write(f"{relationship_pct}%")
    output.write("""</div>
                <div class="stat-secondary">""")
    output.write(f"{complete_relationships} of {total_relationships} complete")
    output.write("""</div>
                <div class="progress-bar">
                    <div class="progress-fill" style="width: """)
    output.write(f"{relationship_pct}%")
    output.write(""""></div>
                </div>
            </div>
        </div>
""")

    # Attention items
    if incomplete_concepts or orphan_count > 0:
        output.write("""
        <section>
            <h2>Needs Attention</h2>
            <div class="attention-list">
""")

        if stub_concepts > 0:
            output.write("""
                <div class="attention-item error">
                    <div class="attention-title">⚠️ """)
            output.write(
                f"{stub_concepts} Stub Concept{'s' if stub_concepts != 1 else ''}"
            )
            output.write("""</div>
                    <div class="attention-detail">These concepts were auto-generated and need definitions, owners, and domains.</div>
                </div>
""")

        if draft_concepts > 0:
            output.write("""
                <div class="attention-item warning">
                    <div class="attention-title">◐ """)
            output.write(
                f"{draft_concepts} Draft Concept{'s' if draft_concepts != 1 else ''}"
            )
            output.write("""</div>
                    <div class="attention-detail">These concepts have no implementing models yet.</div>
                </div>
""")

        if incomplete_concepts:
            output.write("""
                <div class="attention-item warning">
                    <div class="attention-title">📝 """)
            output.write(
                f"{len(incomplete_concepts)} Concept{'s' if len(incomplete_concepts) != 1 else ''} Missing Attributes"
            )
            output.write("""</div>
                    <div class="attention-detail">""")
            for _cid, c in incomplete_concepts[:5]:
                missing = []
                if not c.domain:
                    missing.append("domain")
                if not c.owner:
                    missing.append("owner")
                if not c.definition:
                    missing.append("definition")
                output.write(f"<strong>{c.name}</strong>: {', '.join(missing)}<br>")
            if len(incomplete_concepts) > 5:
                output.write(f"...and {len(incomplete_concepts) - 5} more")
            output.write("""</div>
                </div>
""")

        if orphan_count > 0:
            output.write("""
                <div class="attention-item">
                    <div class="attention-title">🔍 """)
            output.write(
                f"{orphan_count} Orphan Model{'s' if orphan_count != 1 else ''}"
            )
            output.write("""</div>
                    <div class="attention-detail">dbt models without concept tags. Run <code>dbt-conceptual sync</code> to discover them.</div>
                </div>
""")

        output.write("""
            </div>
        </section>
""")

    # Concepts by domain
    output.write("""
        <section>
            <h2>Concepts by Domain</h2>
""")

    for domain_id in sorted(domain_groups.keys()):
        concepts = domain_groups[domain_id]
        domain_name = domain_id
        if domain_id in state.domains:
            domain_name = (
                state.domains[domain_id].display_name or state.domains[domain_id].name
            )

        output.write("""
            <div class="domain-section">
                <div class="domain-header">""")
        output.write(domain_name)
        output.write(f" ({len(concepts)})")
        output.write("""</div>
                <div class="concept-list">
""")

        for _concept_id, concept in sorted(concepts, key=lambda x: x[1].name):
            output.write("""
                    <div class="concept-item">
                        <div>
                            <div class="concept-name">""")
            output.write(concept.name)
            output.write("""</div>
                            <div class="concept-meta">""")

            # Show model count
            model_count = len(concept.models)
            if model_count > 0:
                output.write(f"Models: {model_count}")
                if concept.owner:
                    output.write(f" | Owner: {concept.owner}")
            elif concept.owner:
                output.write(f"Owner: {concept.owner}")
            else:
                output.write("No implementations")

            output.write("""</div>
                        </div>
                        <span class="concept-status """)
            output.write(concept.status or "draft")
            output.write("""">""")
            output.write(concept.status or "draft")
            output.write("""</span>
                    </div>
""")

        output.write("""
                </div>
            </div>
""")

    output.write("""
        </section>
""")

    # Orphan models section
    if orphan_count > 0:
        output.write("""
        <section>
            <h2>Orphan Models</h2>
            <p style="color: #666; margin-bottom: 1rem; font-size: 0.875rem;">
                These models lack meta.concept tags.
            </p>
            <div class="orphan-list">
""")

        for orphan in sorted(state.orphan_models, key=lambda o: o.name):
            output.write("""
                <div class="orphan-item">""")
            output.write(orphan.name)
            output.write("""</div>
""")

        output.write("""
            </div>
        </section>
""")

    output.write(HTML_CLOSE)
